/**
 * Sigma Rule Export Utility
 * Exports the user's detection rule as a valid .yml file download.
 *
 * Security:
 * - The user's rule text is treated as opaque bytes for download (never executed).
 * - Filename is sanitised to alphanumeric + hyphens only.
 * - Metadata injected into the YAML header is escaped to prevent YAML injection.
 * - Uses the Blob API for client-side file generation — no server involvement.
 */

/**
 * Sanitise a string for safe inclusion as a YAML scalar value.
 * Wraps in double quotes and escapes backslashes and double-quotes.
 *
 * @param {string} value
 * @returns {string}
 */
const yamlString = (value) => {
  if (!value || typeof value !== 'string') return '""';
  const escaped = value
    .slice(0, 500) // cap length
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\r?\n/g, ' '); // flatten to single line for header fields
  return `"${escaped}"`;
};

/**
 * Build a safe filename from a scenario title.
 * Allows: lowercase alphanumeric, hyphens, underscores. Max 80 chars.
 *
 * @param {string} title
 * @returns {string}
 */
const safeFilename = (title) => {
  return (title || 'detection_rule')
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, 80) || 'detection_rule';
};

/**
 * Build the YAML header block from scenario metadata.
 * All values are safely quoted.
 *
 * @param {Object} scenario - Current scenario object
 * @returns {string} YAML header lines
 */
const buildHeader = (scenario) => {
  const title = yamlString(scenario?.title || 'Custom Detection Rule');
  const status = 'experimental';
  const description = yamlString(
    scenario?.mitre?.technique
      ? `Detection rule for ${scenario.mitre.technique} (${scenario.mitre.tactic || 'unknown tactic'})`
      : 'Custom detection rule written in DetectSim'
  );
  const level = scenario?.level === 3 ? 'high' : scenario?.level === 2 ? 'medium' : 'low';
  const mitreTechnique = scenario?.mitre?.technique
    ? `\n    - attack.${scenario.mitre.technique.toLowerCase().replace(/[^a-z0-9.]/g, '_')}`
    : '';

  return [
    `title: ${title}`,
    `id: # fill in a UUID`,
    `status: ${status}`,
    `description: ${description}`,
    `references:`,
    `    - https://attack.mitre.org/`,
    `author: DetectSim Operative`,
    `date: ${new Date().toISOString().slice(0, 10)}`,
    `tags:${mitreTechnique || '\n    - attack.unknown'}`,
    `level: ${level}`,
    `falsepositives:`,
    `    - Legitimate administrative activity`,
  ].join('\n');
};

/**
 * Compose the full exportable YAML content.
 *
 * @param {string} ruleText - The raw YAML from the user's editor
 * @param {Object} scenario - Current scenario metadata
 * @returns {string} Complete YAML string
 */
export const buildExportYAML = (ruleText, scenario) => {
  if (!ruleText || typeof ruleText !== 'string') {
    throw new Error('No rule content to export');
  }

  const header = buildHeader(scenario);
  const body = ruleText.trim();

  return [
    '# ─── Sigma Detection Rule ────────────────────────────────────────────────────',
    '# Generated by DetectSim  |  https://github.com/detectsim',
    '# Validate at: https://sigmatools.readthedocs.io/',
    '# ─────────────────────────────────────────────────────────────────────────────',
    '',
    header,
    '',
    body,
  ].join('\n');
};

/**
 * Trigger a browser download of the Sigma rule as a .yml file.
 *
 * @param {string} ruleText - Content of the user's rule editor
 * @param {Object} scenario - Current scenario object (for metadata + filename)
 * @returns {{ success: boolean, filename?: string, error?: string }}
 */
export const exportSigmaRule = (ruleText, scenario) => {
  try {
    const yaml = buildExportYAML(ruleText, scenario);
    const filename = `${safeFilename(scenario?.title)}.yml`;

    const blob = new Blob([yaml], { type: 'text/plain;charset=utf-8' });

    // Create a temporary anchor element and click it
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = filename;
    anchor.style.display = 'none';
    document.body.appendChild(anchor);
    anchor.click();

    // Clean up — revoke object URL after download is triggered
    setTimeout(() => {
      document.body.removeChild(anchor);
      URL.revokeObjectURL(url);
    }, 100);

    return { success: true, filename };
  } catch (error) {
    return { success: false, error: error.message };
  }
};

export default exportSigmaRule;
